### ISSUE TITLE
Remove bungeecord config's connection-throttle to -1 advice

### ISSUE THREAD

**Issue by Janmm14** [xxyy/quietcord#4]
Bungee connection throttle is currently disabled so it can be safely ignored, but setting that to -1 allowes join bots to harrass bungee.

**Comment by Janmm14** [comment]
Suggestion is placed in the config.yml comment.

**Comment by xxyy** [comment]
I put it there so clearly so that there's no chance of confusion. Also, you say that it's currently disabled. In the next sentence, you claim that setting it to -1 causes harm. How does that fit together? The reason I put it there is because I investigated on this kind of edge case and most people had it fixed after setting the value. That one is only in the plugin because somebody needed it.

**Comment by Janmm14** [comment]
> but setting that to -1 allowes join bots to harrass bungee.

Once the feature is available again and the user doesn't change it back. There is no need of setting the bungeecord throttle to -1.
