### ISSUE TITLE
Not working with bungeecord-1119

### ISSUE THREAD

**Issue by jeffmdun** [xxyy/quietcord#7]
Using QuietCord and it doesnt get rid of the Intialhandler has connected thing. 

Using this version of bungeecord: https://yivesmirror.com/grab/bungeecord/BungeeCord-1119.jar

With latest version of QuietCord: 1.0

If this could get fixed that would be fantastic!

**Comment by xxyy** [comment]
Hi, thanks for your bug report! Sadly, I have been unable to reproduce this behaviour with both the latest BungeeCord version as well as the version you provided.

Please verify that your server log contains the following important messages:
````
18:45:40 [INFO] [QuietCord] This logger is now filtered by InitialHandlerFilter{filterPings=true, filterJoins=false}
18:45:40 [INFO] Enabled plugin QuietCord version 1.0-git-00f2196 by Literallie
````

![2018-02-23_18 02 19](https://user-images.githubusercontent.com/547070/36608804-327aa2ec-18cb-11e8-87c0-77656a11e7f5.png)


Can you try to reproduce the problem in a minimal clean install (it didn't occur for me in such an installation)? If the problem doesn't appear there, please provide your full BungeeCord startup log up to the point where the wrong message appears, your QuietCord configuration file, and the list of other BungeeCord plugins you're using, so that we can figure out the cause.

**Comment by xxyy** [comment]
Sorry, you were right – I assumed that the build number from your website would match the official build numbers, but apparently they don't… The official build 1119 works, but the mirrored one doesn't. 

You could try using the official build from here for now: https://ci.md-5.net/job/BungeeCord/1119/

**Comment by xxyy** [comment]
Okay, next update: I haven't worked with this plugin in a while. The `InitialHandler has connected` messages aren't blocked for joins by default because they may provide valuable debug information. These look like this:
````
18:17:59 [INFO] [Literallie] <-> InitialHandler has connected
````
If you wish to turn these off, set `filter.initialhandler.join` to true in `plugins/QuietCord/config.yml`. 

If, however, you were referring to these messages (note the IP address), we're looking at a bug:
````
18:17:51 [INFO] [/127.0.0.1:50046] <-> InitialHandler has connected
````

Please report back with whether this was the issue, and if not, the server logs and configuration file.

**Comment by jeffmdun** [comment]
Still getting the initialhandler has connected thing even with the bungeecord you have sent me.

**Comment by xxyy** [comment]
Please read the other comments too, especially the last one.

**Comment by xxyy** [comment]
I'm sorry, that reply was a little rude. What I meant to say was, please show the configuration file (`plugins/CommandBlockerUltimate/config.yml`) that is causing the issue and the exact messages that are wrongly getting through.
